### ISSUE TITLE
Android crash while idle

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu-framework#2669]
**Describe the crash:** opened osu, been idle for 2 minutes, and crash

**osu!lazer version:** 438a294

**Logs:** Android crash report
```
android.runtime.JavaProxyThrowable: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
  at osuTK.FrameEventArgs.set_Time (System.Double value) [0x0000c] in <83afe94143fd4c7099c83433d9fcfcc4>:0 
  at osuTK.Android.AndroidGameView.RunIteration (System.Threading.CancellationToken token) [0x00045] in <7484b4753167456b82f11e78c0669d25>:0 
  at osuTK.Android.AndroidGameView+<>c__DisplayClass58_0.<StartThread>b__2 (System.Object _) [0x00000] in <7484b4753167456b82f11e78c0669d25>:0 
  at Android.App.SyncContext+<>c__DisplayClass3_0.<Send>b__0 () [0x00000] in <95d915721ad748108ff096dce8f8f32c>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <95d915721ad748108ff096dce8f8f32c>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <95d915721ad748108ff096dce8f8f32c>:0 
  at (wrapper dynamic-method) System.Object.19(intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

**Computer Specifications:** 
Xiaomi Redmi 5a
Android 7.1.2
Ram 2.0 GB
Processor 4x1.40ghz

**Comment by ticotaco72** [comment]
Interesting

I reproduced it next time and I looked into logs and there was in performance.log this 2 sec before crash
2019-08-31 03:17:13: TextureAtlas size exceeded 4 time(s); generating new texture (1024x1024)

**Comment by ticotaco72** [comment]
probably should go out of milestone, as mobile isn't on current agenda

**Comment by miterosan** [comment]
Could potentially be fixed by just changing line 543 in https://github.com/ppy/osuTK/blob/master/src/osuTK.Android/AndroidGameView.cs#L543

````csharp
-               var t = (curUpdateTime - prevUpdateTime).TotalSeconds;
-               updateEventArgs.Time = t;

+               var t = (curUpdateTime - prevUpdateTime).TotalSeconds;
+               updateEventArgs.Time = Math.Max(1, t);
````
If totalSeconds is less than 1 it creates the OutOfRangeException in https://github.com/ppy/osuTK/blob/master/src/osuTK/FrameEventArgs.cs#L62

**Comment by bdach** [comment]
that sounds utterly wrong. first off, if `t` is 0 precisely, then that implies `curUpdateTime == prevUpdateTime` which is already worrying. leaving even that aside, judging from the unit, that would mean that `UpdateFrameInternal()` would run with a `Time` never less than *1 second*, which in a game is 60 frames at least and sounds like it would break absolutely everything.

**Comment by miterosan** [comment]
Forgot that TotalSeconds is double. Yeah, nevermind my suggestion.

**Comment by peppy** [comment]
@miterosan did you repro this one? or confirm it's still an issue?

**Comment by bdach** [comment]
I've just randomly hit this crash today while testing android things - but looks like the pull linked above hasn't made it over to framework, as the csproj lists version 173:

https://github.com/ppy/osu-framework/blob/c2757c68365f798b2c6f2f005f8d19a03fe6d7a3/osu.Framework.Android/osu.Framework.Android.csproj#L26

while the latest [appveyor build](https://ci.appveyor.com/project/peppy/opentk) says it should be 177 (`ppy.osuTK.NS20` packages installed in framework projects also use that number). The corresponding `osuTK.Android` version hasn't been uploaded to nuget yet it seems.

**Comment by peppy** [comment]
sounds like it must have failed compilation, will look into it.

**Comment by peppy** [comment]
The cause of this is our deployments failing to upload symbols packages specifically. This has been going on for some time now, so I'd say it's not important that we upload symbols in the first place. I'm going to disable that and do a new deploy (`1.0.178`).

**Comment by bdach** [comment]
Given the bump has happened now, tentatively closing. If someone hits this again please comment here and this'll be reopened.
