### ISSUE TITLE
Cursor stuck top left when leaving game when it's fullscreen & raw input

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu-framework#4050]
https://youtu.be/CX7_A6Ylyaw (first part is fullscreen, second is borderless)

[DxDiag.txt](https://github.com/ppy/osu-framework/files/5623650/DxDiag.txt)

**Comment by bdach** [comment]
What pointing device is this? Mouse, tablet? dxdiag lists multiple.

**Comment by LittleEndu** [comment]
Both are stuck. Tablet does move the cursor freely but any cycle where there is no input from the tablet it goes back to top left.

**Comment by LittleEndu** [comment]
It doesn't seem to. Unplugging the mouse didn't fix, unplugging the tablet didn't fix. Worth noting (and I think this might even invalidate the issue) is that I'm not on vendor software, I'm using hawku drivers. But the issue persist when I uninstall the driver and let windows grab generic driver after plugging the tablet back in.

**Comment by bdach** [comment]
I can't say I tested SDL on windows but it really ought to be working with *some* device...

**Comment by nbvdkamp** [comment]
I encountered this too on Windows with only mouse (don't own a tablet), upon following an external URL so it seems to be unrelated to tablets. It can get stuck in the corner of either monitor in multi monitor setups.

**Comment by peppy** [comment]
Just to confirm, this only occurs until you alt-tab cycle once, after which point it's fixed?

**Comment by Joehuu** [comment]
Okay, first off the PR doesn't fix the issue.

From my findings on Windows 10, I can now reproduce on framework by a different method. It needs to be windowed, and raw input needs to be on. Then, you need to move the cursor really fast inside and press `WIN-D`. The cursor will then teleport to the top left, but it won't get stuck.
![SQqdwloMUS](https://user-images.githubusercontent.com/35318437/100843930-ef6df480-342f-11eb-9278-56154be1ca27.gif)

On lazer, I can also reproduce on windowed with raw input by pressing `WIN-D`. Cursor still gets stuck though.
![ETERgwPyW3](https://user-images.githubusercontent.com/35318437/100844139-4378d900-3430-11eb-98e1-094aab14a3db.gif)

> Just to confirm, this only occurs until you alt-tab cycle once, after which point it's fixed?

Nope, for the fullscreen reproduction, you just need to minimize fullscreen in any way (alt-tab, win-d, etc.) and it'll never recover.

**Comment by peppy** [comment]
This looks to be an internal bug in SDL2, specific to the use of winkey+D. I'm guessing they are using similar logic to what we were prior to #4056.

I guess I'll report this over their way, but there's not much we can seemingly do to fix this (i've tried a few different methods of fixing locally, but the grab commands seem to have *no effect* after a winkey+D cycle until next focus loss).

**Comment by peppy** [comment]
For the record, I've tried:

- Applying the grab change inside WINDOW_EXPOSE or MOUSE_ENTERED
- Applying the grab change in the main loop, every loop (with a preceding `false` to ensure SDL isn't keeping some internal state)

Based on both of these failing it seems like something internal to SDL is tracking window active state incorrectly, as I suggest above.

**Comment by peppy** [comment]
A potential solution to this is to manage cursor confining using OsuTK (will require exposing or copying the implementation across) aka direct win32 calls. Should only be around 10-20 lines of code.

**Comment by bdach** [comment]
Can everyone that experienced this confirm that it's resolved in the latest release with the PR linked above (https://github.com/ppy/osu/pull/11060)?

**Comment by Joehuu** [comment]
Yep, the cursor doesn't get stuck now. But as said in the PR description, it can still teleport to the top left side when moving cursor really fast in the window and pressing win-d (https://github.com/ppy/osu-framework/issues/4050#issuecomment-737060233).

**Comment by Anonymous-osuplayer** [comment]
It happens the same to me, but it happens every time when I press alt+tab on fullscreen with raw input enabled
